---
abstract: navel-dispatcher-manager
author:
  - 'Yoann Le Garff, Nicolas Boquet and Yann Le Bras'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: apache_2_0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Navel-Dispatcher
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent::HTTP: '0'
  File::ShareDir: '0'
  JSON::Validator: '0'
  Mojolicious: '0'
  Navel::API: '0'
  AnyEvent::Fork::RPC::Serializer::Cpanel::JSON::XS: '0'
  Navel::AnyEvent::Pool: '0'
  Navel::Base: '0'
  Navel::Base::WorkerManager: '0'
  Navel::Definition::Dispatcher: '0'
  Navel::Event: '0'
  Navel::Logger: '0'
  Navel::Mojolicious::Plugin::Logger: '0'
  Navel::Mojolicious::Plugin::OpenAPI::StdResponses: '0'
  Navel::Notification: '0'
  Navel::Queue: '0'
  perl: v5.18.0
  Promises: '0'
  URI: '0'
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.html
  repository: http://github.com/Navel-IT/navel-dispatcher-manager
version: '0.1'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
